GET http://localhost:4000/ping

###
GET http://localhost:4000/eventos

###
GET http://localhost:4000/eventos/evento-fullstack

###
GET http://localhost:4000/eventos/53ae44ec-30fb-4e5a-9b0b-a9fbedd8e3c1
